# Numpy Cheat Sheet

In [1]:
import numpy as np

_divider = "".join(["-" for _ in range(73)])


## Creating Arrays

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Dimensions & Shape

Retrieve number of dimensions with `obj.ndim`

In [4]:
a.ndim

1

In [5]:
b.shape

(2, 3)

## Types & Sizes

In [6]:
a.dtype

dtype('int64')

Get size in bytes with `array.itemsize`

In [7]:
a.itemsize

8

Get number of elements in an array with `array.size`. You can get size of the entire array in bytes with `array.itemsize` * `array.itemsize`.

In [8]:
size = a.size
item_size = a.itemsize
total_byte_size = size * item_size

print(f'Size: {size}')
print(f'Item size: {item_size}')
print(f'Total byte size: {total_byte_size}')

Size: 3
Item size: 8
Total byte size: 24


Get total byte size with `array.nbytes`.

In [9]:
print(a.nbytes)

24


## Accessing & Changing Elements

In [10]:
list_one = np.arange(10)
list_two =np.arange(10, 20)
arr = np.array([list_one, list_two])

print("List one:")
print(list_one)
print(_divider)
print("List two:")
print(list_two)
print(_divider)
print("Array:")
print(arr)

List one:
[0 1 2 3 4 5 6 7 8 9]
-------------------------------------------------------------------------
List two:
[10 11 12 13 14 15 16 17 18 19]
-------------------------------------------------------------------------
Array:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


Get specific element [row, column].

In [11]:
arr[1, 5]

15

Get specific element with negative values.

In [12]:
arr[0, -1]

9

Get a specific row.

In [13]:
print(arr[0,:])

[0 1 2 3 4 5 6 7 8 9]


Get a specific column.

In [14]:
print(arr[:, 1])

[ 1 11]


Array slicing - [start index : end index : step size]

In [15]:
print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print("Row: 0 (first row)")
print("Start: second element")
print("Stop: last element")
print("Step size: 2 (every other element)")
print(arr[0, 1:-1:2])

STARTING ARRAY
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
-------------------------------------------------------------------------
ENDING ARRAY
Row: 0 (first row)
Start: second element
Stop: last element
Step size: 2 (every other element)
[1 3 5 7]


Changing items.

In [16]:
arr_updated = arr.copy()
arr_updated[1, -1] = 1000

print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print(arr_updated)

STARTING ARRAY
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
-------------------------------------------------------------------------
ENDING ARRAY
[[   0    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18 1000]]


Changing multiple items with subsequencing.

In [17]:
arr_updated = arr.copy()
arr_updated[:, 2] = [1, 2]

print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print(arr_updated)

STARTING ARRAY
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
-------------------------------------------------------------------------
ENDING ARRAY
[[ 0  1  1  3  4  5  6  7  8  9]
 [10 11  2 13 14 15 16 17 18 19]]


3D array example.

In [18]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Get element from 3D array (work outside in).

In [19]:
print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print(arr[0, 1, 1])

STARTING ARRAY
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------------------------------------------------------
ENDING ARRAY
4


Slicing 3D array.

In [20]:
print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print("Elements: all")
print("Rows: first of each element")
print("Columns: last column")
print(arr[:, 0, -1])

STARTING ARRAY
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------------------------------------------------------
ENDING ARRAY
Elements: all
Rows: first of each element
Columns: last column
[2 6]


Replacing elements in 3D array.

In [21]:
arr_updated = arr.copy()
arr_updated[1, -1] = 1000

print("STARTING ARRAY")
print(arr)
print(_divider)
print("ENDING ARRAY")
print(arr_updated)

STARTING ARRAY
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------------------------------------------------------
ENDING ARRAY
[[[   1    2]
  [   3    4]]

 [[   5    6]
  [1000 1000]]]
